include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
    image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master'
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.codeberg.lapingvino.Accolade.json"
        MESON_ARGS: "-Dprofile=Devel"
        FLATPAK_MODULE: "accolade"
        APP_ID: "org.codeberg.lapingvino.Accolade"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        BUNDLE: "accolade-dev.flatpak"
    extends: .flatpak
